### PR TITLE
Add Solarized patch

### PR DESCRIPTION
**Pull request by naortega**
I've taken the liberty of adding in the conditions for the three different [solarized patches](http://st.suckless.org/patches/solarized/) (dark, light, and both). There does seem to be some overlap with `ALPHA_FOCUS_HIGHLIGHT_PATCH` regarding the `defaultbg` value. Shouldn't be an issue so long as the user doesn't want both at once.

### CODE REVIEW

**Comment by naortega** [comment]
I just noticed an entry for this patches should be added to the README. Tell me if you want this added, or if this'll be done after the PR is merged.

**Comment by bakkeby** [comment]
Don't worry about the README.

In general I have avoided including patches that are practically only changes to the configuration file, as in you'd expect someone using the tool to be capable of making changes to config.h. 

There are like ten or so of these theme patches so if I am going to include that in st-flexipatch then I'll have to find a better solution than to have everything in config.def.h, probably a mechanism of sourcing the theme instead.

Using Xresources, pywal or theme.sh are obvious alternative methods of managing the theme.

Maybe I'll find time later this week to look into this in more detail, have some other stuff taking priority at the moment.

**Comment by naortega** [comment]
Makes sense. If there's something I can help with I wouldn't mind lending a hand.

**Comment by naortega** [comment]
Taking a look at theme.sh, I think it's much more inline with the kind of computing I wanna do. I hadn't heard of it before, and I think it helps to modularize things quite a bit. I'll leave this PR open just in case you want it, but I think that truly solves the issue.

**Pull request closed without merging**
