### PR TITLE
Add selectioncolors patch

### PR DESCRIPTION
**Pull request by JCallicoat**
Changes mode in Glyph struct from ushort to uint32_t per https://github.com/bakkeby/st-flexipatch/issues/91#issuecomment-1918439030 and adds latest version of selectioncolors patch.

### CODE REVIEW

**Comment by veltza** [comment]
Sorry to interrupt, but it looks like the **bit 14** is still free in the glyph attributes. So there should be no need to increase the size of the bitfield.

**Comment by JCallicoat** [comment]
> Sorry to interrupt, but it looks like the **bit 14** is still free in the glyph attributes. So there should be no need to increase the size of the bitfield.

Oh looks like you are right, nice catch. @bakkeby should I back out the change to uint32_t and just use bit 14 here and you can deal with increasing the size if needed for other patches in the future?

**Comment by bakkeby** [comment]
Yes let's just use bit 14 then and change the data type later if needed. The code changes themselves look good.

There is potentially a conflict with the dynamic cursor color patch, but not sure how one might expect them to work together in this context so probably fine letting selection colors take precedence here.

**Comment by JCallicoat** [comment]
Done.

**Comment by bakkeby** [comment]
Thanks @JCallicoat.

**Pull request merged**
