### PR TITLE
scrollback: add an option to disable keys on the alt screen

### PR DESCRIPTION
**Pull request by veltza**
Modern terminals like Alacritty, Kitty, Gnome-terminal, etc. don't allow you to access the scrollback buffer from the alternative screen, which makes sense because the alt screen is a kind of sandbox for cli applications. Only old terminals like xterm and the st scrollback patch allow you to do so.

This is not a big deal, but the problem is that the scrollback keybindings can conflict with other applications on the alt screen. For example, if you want to use Alt-j/k keys to navigate the scrollback buffer, you can't use those keybindings in other applications like vim and tmux. The new option will disable the scrollback keys on the alt screen, so they won't conflict anymore.

By default, the option is turned off, so it won't change the current behaviour and it won't affect the scrolling wheel at all.

Ideally, we would have an option in the shortcuts table to enable or disable any key on any screen. It would be very easy to implement, but there aren't that many patches that would benefit from it right now.

### CODE REVIEW

**Comment by bakkeby** [comment]
> Ideally, we would have an option in the shortcuts table to enable or disable any key on any screen.

I would agree with this. I wouldn't actually mind making an exception and include that by default even if that strays from upstream st.

The universcroll patch adds an alt option for the `mshortcuts` config and uses this in the `mouseaction` function. In principle using that one could get rid of the `maltshortcuts` array introduced by the altscreen variant of the scrollback mouse patch. I suppose something similar could be added for the keyboard `shortcuts` as well.

**Comment by veltza** [comment]
> The universcroll patch adds an alt option for the mshortcuts config and uses this in the mouseaction function. In principle using that one could get rid of the maltshortcuts array introduced by the altscreen variant of the scrollback mouse patch. I suppose something similar could be added for the keyboard shortcuts as well.

That was exactly in my mind, and my idea is pretty much the same as that, but instead of using nasty magic numbers, we could use meaningful constants to make it more user-friendly. Should we leave this open and start discussion on the discussion page, or should we discuss here how to implement that handler?

**Comment by bakkeby** [comment]
Either is fine. If we go with a different approach then this pull request will be redundant anyway.

**Comment by veltza** [comment]
Let's continue here. Here is my first draft, and it would be as simple as this.

```diff
diff --git a/config.def.h b/config.def.h
index 8e36213..3166c2a 100644
--- a/config.def.h
+++ b/config.def.h
@@ -334,6 +334,11 @@ ResourcePref resources[] = {
  */
 static uint forcemousemod = ShiftMask;
 
+/* Screens */
+#define S_PRI 1     /* the primary screen */
+#define S_ALT 2     /* the alternative screen */
+#define S_ALL 0     /* all screens */
+
 /*
  * Internal mouse shortcuts.
  * Beware that overloading Button1 will disable the selection.
@@ -398,7 +403,7 @@ static char *setbgcolorcmd[] = { "/bin/sh", "-c",
 #endif // EXTERNALPIPE_PATCH
 
 static Shortcut shortcuts[] = {
-	/* mask                 keysym          function         argument */
+	/* mask                 keysym          function         argument  screens */
 	{ XK_ANY_MOD,           XK_Break,       sendbreak,       {.i =  0} },
 	{ ControlMask,          XK_Print,       toggleprinter,   {.i =  0} },
 	{ ShiftMask,            XK_Print,       printscreen,     {.i =  0} },
@@ -409,8 +414,8 @@ static Shortcut shortcuts[] = {
 	{ TERMMOD,              XK_C,           clipcopy,        {.i =  0} },
 	{ TERMMOD,              XK_V,           clippaste,       {.i =  0} },
 	#if SCROLLBACK_PATCH
-	{ ShiftMask,            XK_Page_Up,     kscrollup,       {.i = -1} },
-	{ ShiftMask,            XK_Page_Down,   kscrolldown,     {.i = -1} },
+	{ ShiftMask,            XK_Page_Up,     kscrollup,       {.i = -1}, S_PRI},
+	{ ShiftMask,            XK_Page_Down,   kscrolldown,     {.i = -1}, S_PRI},
 	#endif // SCROLLBACK_PATCH
 	#if CLIPBOARD_PATCH
 	{ TERMMOD,              XK_Y,           clippaste,       {.i =  0} },
diff --git a/st.h b/st.h
index e4db7ea..bf036a7 100644
--- a/st.h
+++ b/st.h
@@ -251,6 +251,7 @@ typedef struct {
 	KeySym keysym;
 	void (*func)(const Arg *);
 	const Arg arg;
+	int screens;
 } Shortcut;
 
 typedef struct {
diff --git a/x.c b/x.c
index a05d9cb..eca57e8 100644
--- a/x.c
+++ b/x.c
@@ -3165,9 +3165,12 @@ kpress(XEvent *ev)
 	}
 	#endif // VIM_BROWSE_PATCH
 
+	int screen = tisaltscr() + 1;
+
 	/* 1. shortcuts */
 	for (bp = shortcuts; bp < shortcuts + LEN(shortcuts); bp++) {
-		if (ksym == bp->keysym && match(bp->mod, e->state)) {
+		if (ksym == bp->keysym && match(bp->mod, e->state) &&
+			    (!bp->screens || bp->screens & screen)) {
 			bp->func(&(bp->arg));
 			return;
 		}
```

The tisaltscr () function must be moved to st.c/h, so it will always be available.

**Comment by veltza** [comment]
> #define S_PRI 1     /* the primary screen */
#define S_ALT 2     /* the alternative screen */
#define S_ALL 0     /* all screens */

Even though these constant values would be better for bit-wise operations, I think we should keep backward compatibility and use the same constant values that the universcroll patch is using. So the implementation would be the same for keyboard shortcuts. Here is the final draft.

```diff
diff --git a/config.def.h b/config.def.h
index 8e36213..0901c38 100644
--- a/config.def.h
+++ b/config.def.h
@@ -398,7 +398,7 @@ static char *setbgcolorcmd[] = { "/bin/sh", "-c",
 #endif // EXTERNALPIPE_PATCH
 
 static Shortcut shortcuts[] = {
-	/* mask                 keysym          function         argument */
+	/* mask                 keysym          function         argument  screen */
 	{ XK_ANY_MOD,           XK_Break,       sendbreak,       {.i =  0} },
 	{ ControlMask,          XK_Print,       toggleprinter,   {.i =  0} },
 	{ ShiftMask,            XK_Print,       printscreen,     {.i =  0} },
@@ -409,8 +409,8 @@ static Shortcut shortcuts[] = {
 	{ TERMMOD,              XK_C,           clipcopy,        {.i =  0} },
 	{ TERMMOD,              XK_V,           clippaste,       {.i =  0} },
 	#if SCROLLBACK_PATCH
-	{ ShiftMask,            XK_Page_Up,     kscrollup,       {.i = -1} },
-	{ ShiftMask,            XK_Page_Down,   kscrolldown,     {.i = -1} },
+	{ ShiftMask,            XK_Page_Up,     kscrollup,       {.i = -1}, S_PRI},
+	{ ShiftMask,            XK_Page_Down,   kscrolldown,     {.i = -1}, S_PRI},
 	#endif // SCROLLBACK_PATCH
 	#if CLIPBOARD_PATCH
 	{ TERMMOD,              XK_Y,           clippaste,       {.i =  0} },
diff --git a/st.h b/st.h
index e4db7ea..68b470b 100644
--- a/st.h
+++ b/st.h
@@ -245,12 +245,19 @@ typedef struct {
 	struct timespec tclick2;
 } XSelection;
 
+enum screen {
+	S_PRI = -1, /* primary screen */
+	S_ALT = 1,  /* alternative screen */
+	S_ALL = 0,  /* all screens */
+};
+
 /* types used in config.h */
 typedef struct {
 	uint mod;
 	KeySym keysym;
 	void (*func)(const Arg *);
 	const Arg arg;
+	int screen;
 } Shortcut;
 
 typedef struct {
diff --git a/x.c b/x.c
index a05d9cb..6c3229a 100644
--- a/x.c
+++ b/x.c
@@ -3165,9 +3165,12 @@ kpress(XEvent *ev)
 	}
 	#endif // VIM_BROWSE_PATCH
 
+	int screen = tisaltscr() ? 1 : -1;
+
 	/* 1. shortcuts */
 	for (bp = shortcuts; bp < shortcuts + LEN(shortcuts); bp++) {
-		if (ksym == bp->keysym && match(bp->mod, e->state)) {
+		if (ksym == bp->keysym && match(bp->mod, e->state) &&
+			    (!bp->screen || bp->screen == screen)) {
 			bp->func(&(bp->arg));
 			return;
 		}
```

I believe you can take the wheel now and finish the job. I'm ready to close this PR.

**Comment by bakkeby** [comment]
I didn't quite like the enum names, but they are in line with all the other enums in the st code base and I couldn't think of anything better. Let me know if you spot anything I might have missed.

**Comment by veltza** [comment]
> I didn't quite like the enum names, but they are in line with all the other enums in the st code base and I couldn't think of anything better. Let me know if you spot anything I might have missed.

I was just thinking about short names, but maybe more descriptive and different naming conventions would have been better. For example, PRI_SCR, ALT_SCR or something. I don't know.

Other than that, everything works and looks good to me. Even mouse shortcuts are more configurable now. This is more than I hoped for. Thanks!

**Pull request closed without merging**
