### PR TITLE
Change Ctrl+l behaviour

### PR DESCRIPTION
**Pull request by veltza**
Old behaviour:

- clear clears the screen and the scrollback buffer
- ctrl+l (or clear -x) clears the screen and the scrollback buffer

$ clear | od -t a
0000000 esc   [   H esc   [   3   J

$ clear -x | od -t a
0000000 esc   [   H esc   [   3   J

New behaviour:

- clear clears the screen and the scrollback buffer
- ctrl+l (or clear -x) scrolls up the screen and preserves the scrollback buffer

$ clear | od -t a
0000000 esc   [   H esc   [   2   J esc   [   3   J

$ clear -x | od -t a
0000000 esc   [   H esc   [   2   J

I opted to choose to scroll up the whole screen because it was easier to implement and it works with Sixel and most like other patches too. So it's working exactly like vte based terminals, but a little bit differently than Alacritty, which scrolls up the content only. It shouldn't be too hard to implement the Alacritty's implementation too, but let's try this first.

Notes
- I removed the scrollback code from the tscrolldown function because that function shouldn't be using the scrollback buffer at all
- There are some other minor fixes too and most of them are related to Columns patch
- Sixel and Vim Browse patches don't work together because there are serious scrolling issues which are unrelated to this PR. I guess nobody is using these patches together because scrolling has been broken for a long time. I may have a solution for it too, but that would be a separate PR.

### CODE REVIEW

**Comment by bakkeby** [comment]
These changes looks surprisingly solid. It is a bit odd though how when using Ctrl+l or clear the screen scrolls such that the prompt is at the very top, but all the empty space that was visible below the prompt becomes part of the history - i.e. if you scroll up there will be an empty gap before you get to the history.

This is even more obvious if you hit Ctrl+l a few times.

**Comment by veltza** [comment]
Like I said, I opted to choose to scroll up the whole screen (including empty lines) because it was easier to implement (just one line of code). For example, Xfce terminal works exactly like that when you press ctrl+l.

I can implement Alacritty's implementation too, which will scroll the content into scrollback and not those empty lines at the bottom of the screen. That would need some extra lines of code and would be a little bit trickier to implement. Do you think that implementation would be preferable?

**Comment by bakkeby** [comment]
Well as-is it is better than the existing behaviour in any case. My first impression was that it was merely about adjusting the history index and number of items in the history, but I may very well be wrong about that.

**Comment by bakkeby** [comment]
If you find it to be too troublesome then leave it.  Can always revisit later if need be.

**Comment by veltza** [comment]
Here is the updated version for testing.

**Comment by veltza** [comment]
I think I am ready now.

**Comment by bakkeby** [comment]
I cross checked without any patches, then the scrollback patches, the sixel patch as well as the vim browse patch and the behaviour looks solid across the board for this pull request.

I'd assume that this change would be more tricky to achieve with the columns reflow patch.

Ref. how it originally worked regarding scrolling the whole screen:

> it's working exactly like vte based terminals

I had to check and indeed this is also how it works in gnome-terminal.

Out of interest I checked xterm and there it seems to just clear the screen (including the history / data that is on the current screen).

Regarding the vim browse patch that conflicts with so many things that I'd prefer to remove it from this project. I'd rather see a version of it that merely depends on the scrollback patch if that is at all necessary or relevant.

In any case this works fine as far as I can tell and I see no reason not to merge it.

**Pull request merged**
