### PR TITLE
Adding reflow patch

### LINKED ISSUE #34: [request] Add patch column patch
Hi @bakkeby , st cuts text inside it when st's window is resized :/ . Most terminals dont do this. I didnt find any patches for it either.

I found a [build](https://github.com/BeyondMagic/st) which has this issue fixed , seems like it extends the [patch column](https://github.com/juliusHuelsmann/st-history-vim#patches) from here.

@BeyondMagic 's build didnt provide any patch for it tho , I found some useful commits https://github.com/BeyondMagic/st/commit/4339de9129d7f61aedd754a7346fe1b49d467738.

( st without patch column and with it (beyondmagic's build) )

https://user-images.githubusercontent.com/59060246/126583806-0b484dac-4be4-4e80-87d8-f6f2c1762a2b.mp4 

 It would be very nice if there was a patch for this :]

### PR DESCRIPTION
**Pull request by bakkeby**
This adds the reflow "patch" based on @veltza's implementation.

Closes #34

### CODE REVIEW

**Comment by veltza** [comment]
Now that the reflow and improved keyboard select patches are moving to st-flexipatch, st-sx has very little reason to exist anymore unless I implement the kitty image protocol as well. lol

But we're not there yet because I found the following issues in this PR:

- Cannot compile when only the reflow and keyboard select patches are enabled.

- `highlightfg` and `highlightbg` variables are missing from [config.def.h](https://github.com/veltza/st-sx/blob/ac0ab85b6173bd6d3e5c5005bf801429e321473e/config.def.h#L188-L190) (improved keyboard select patch needs these)

- Sixels disappear from the scrollback when reflow is enabled. This needs to be investigated.

- (Improved) keyboard select does not copy anything to the clipboard unless the clipboard patch is also enabled. This could be fixed like this:

```diff
diff --git a/patch/keyboardselect_reflow_st.c b/patch/keyboardselect_reflow_st.c
index e6b8364..57bfedc 100644
--- a/patch/keyboardselect_reflow_st.c
+++ b/patch/keyboardselect_reflow_st.c
@@ -193,6 +193,10 @@ kbds_copytoclipboard(void)
 		selextend(kbds_c.x, kbds_c.y, kbds_seltype, 1);
 	}
 	xsetsel(getsel());
+
+	#if !CLIPBOARD_PATCH
+	xclipcopy();
+	#endif // !CLIPBOARD_PATCH
 }
 
 void
```

**Comment by bakkeby** [comment]
I'll look into the sixels disappearing from scrollback.

> st-sx has very little reason to exist anymore

I would disagree :). I see it as a fine example implementation.

Due to the general approach st-flexipatch is inevitably a platter of spaghetti code and having a dedicated build sounds more fun to work with. Maybe that will inspire me to roll my own at some point.

**Comment by veltza** [comment]
I just noticed that neither the reflow patch nor st-sx use the ATTR_SELECTED attribute. The attribute came from the [scrollback-reflow](https://st.suckless.org/patches/scrollback/st-scrollback-reflow-0.9.diff) patch, but it's unused there as well.

So, you might want to remove the REFLOW_PATCH condition here to avoid confusion:

```c
	#if SELECTION_COLORS_PATCH || REFLOW_PATCH
	ATTR_SELECTED       = 1 << 12,
	#endif // SELECTION_COLORS_PATCH | REFLOW_PATCH
```

**Comment by bakkeby** [comment]
Done. Thanks for noticing.

**Comment by veltza** [comment]
> I am aware that the keyboard select patch is not actually reflow specific; it is more of an upgrade (or it could be considered as a different patch variant). Didn't want to invest time in backporting that to work with pre-reflow resizing and scrollback behaviour hence added it as a reflow specific option.

Technically, it should be compatible, with minor changes, with the scrollback patch, since they use a very similar scrollback structure with the reflow. In fact, I wrote an early version of the improved variant to work with the scrollback patch. So, if there is demand, I can take a look at it too.

**Pull request merged**
